### PR TITLE
fix(#379): remove unused strings

### PR DESCRIPTION
**Pull request by hamidsafdari**
This removes all the unused strings from the project. I used an Android Studio inspection to find all of the unused strings. Added them back one by one and tried to find if they were really unused (by using Alt+F7). I kept 6 of the strings that Android Studio falsely claims to be unused and removed the rest.

### CODE REVIEW

**Comment by wolpi** [comment]
Can you please update this PR ?
There were open changes from weblate, see #389.

**Comment by hamidsafdari** [comment]
Conflicts resolved.

**Comment by lmagyar** [comment]
I've merged it into my fork, and it works (API 28, Android 9).

OK, "works" means it's not obviously broken, hard to test removed unused content. :)

**Comment by wolpi** [comment]
Thanks!

**Pull request merged**
