### PR TITLE
Updated Gradle + Build-Tools + SDK versions

### PR DESCRIPTION
**Pull request by jlelse**
I updated all of them

### CODE REVIEW

**Comment by licaon-kter** [comment]
Did they fix the problems with SDK 25 in F-Droid?

**Comment by jlelse** [comment]
@licaon-kter oh didn't know

**Comment by wolpi** [comment]
> Did they fix the problems with SDK 25 in F-Droid?

What problems? Do you have a link?

**Comment by wolpi** [comment]
> I updated all of them

It seems that the windows bat file has wrong line endings. What OS do you use? Can you run unix2dos (or similar) and update this PR?

**Comment by jlelse** [comment]
@wolpi I use Linux

**Comment by wolpi** [comment]
I double checked line endings of bat file locally and it is alright. Thanks!

**Pull request merged**
