### PR TITLE
Removes main window back arrow in titlebar

### PR DESCRIPTION
**Pull request by licaon-kter**
Fix https://github.com/wolpi/prim-ftpd/issues/39

### CODE REVIEW

**Comment by wolpi** [comment]
well, that is the easy part :wink: 

what about the menu? :innocent:

**Comment by licaon-kter** [comment]
Which menu are you speaking of?

**Comment by wolpi** [comment]
the menu you mentioned in #39 (in your 2nd comment)

**Comment by licaon-kter** [comment]
Oh, I'd rather side with `one can use the Android provided task manager`.

For 2 reasons:
* my skills got me this far only
* except the log/theme thing, where you have a text explaining the restart need, I don't see any place that *really* needs it

**Comment by wolpi** [comment]
I'll see if I can find a way that eats not too much time to implement. Maybe additonal icons in actionbar or something the like.

**Comment by wolpi** [comment]
Has been changed in the mean time, so I'm closing this now.

**Pull request closed without merging**
