### PR TITLE
Minor features and improvements

### PR DESCRIPTION
**Pull request by codebymikey**
Following on from #58, features include:

- Improving the homescreen widget presentation.
- Anonymous login support.
- Ability to stop the server directly from the notification bar.
- Launch the main activity directly from the widget if a password is required.
- Using event bus to trigger a page refresh without necessarily having to rely on passing the MenuItem objects around.

### CODE REVIEW

**Comment by licaon-kter** [comment]
Wow, massive.

Maybe this was better spit in 5 PRs?

**Comment by wolpi** [comment]
It's just 5 commits, so it is ok to review. If it would be more and smaller commits I would prefer to split it up.

**Comment by codebymikey** [comment]
My laptop harddrive died on me this morning, so I'm currently unable to update the pull request properly.

It shouldn't be too difficult to review the

**Comment by wolpi** [comment]
Dying hardware sucks :sob: 
I'm glad you could push this before :tada:

**Comment by codebymikey** [comment]
Superseded by pull-request https://github.com/wolpi/prim-ftpd/pull/60

**Pull request closed without merging**
